### ISSUE TITLE
I am trying to install EntityFrameworkRuler thru nuget but I get an error

### ISSUE THREAD

**Issue by jdanielpa** [R4ND3LL/EdmxRuler#1]
Im using VS2022 and the project targets .NET6 but when I try to install the package, I get the following errors:

NU1202	Package EntityFrameworkRuler 1.0.28 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package EntityFrameworkRuler 1.0.28 supports:
  - net6.0 (.NETCoreApp,Version=v6.0) / any
  - net7.0 (.NETCoreApp,Version=v7.0) / any

 'EntityFrameworkRuler 1.0.28' has a package type 'DotnetTool' that is not supported by project ...

 NU1212	Invalid project-package combination for EntityFrameworkRuler 1.0.28. DotnetToolReference project style can only contain references of the DotnetTool type

Any ideas on what I am doing wrong?

**Comment by R4ND3LL** [comment]
Looks like you're trying to reference the CLI package.  Reference [Design](https://www.nuget.org/packages/EntityFrameworkRuler.Design/) instead:

> dotnet add package EntityFrameworkRuler.Design 
PM> NuGet\Install-Package EntityFrameworkRuler.Design

**Comment by jdanielpa** [comment]
Thanks.  That installed but now I am not sure my next steps.  Do I need to install the CLI tool using:

PM> NuGet\Install-Package EntityFrameworkRuler

or do I go straight to:
> efruler -g <edmxFilePath> <efCoreProjectBasePath>

Thanks again for the help

**Comment by R4ND3LL** [comment]
To install the CLI tool, run the following from a developer terminal:

> dotnet tool install --global EntityFrameworkRuler 

Then you would use the "efruler -g ..." command to generate the rule file from the EDMX.

However, I may have an easier option for you.  I just published a VS extension that allows you to generate AND edit rules from the UI.   In VS, go to Manage Extensions and search up "Entity Framework Ruler", or go here and download:

[https://marketplace.visualstudio.com/items?itemName=Randell.EF-Ruler](https://marketplace.visualstudio.com/items?itemName=Randell.EF-Ruler)

After install, you just right-click on an EDMX and go to _Convert EDMX to DB Context Rules_. 
![EdmxConverterPreview](https://user-images.githubusercontent.com/65310488/205711045-39a7bc7f-7eb5-42db-b7de-18ed9e3f0f93.png)

Plus, I would appreciate feedback on it.

With the rules.json file in the root of your EF Core project, and the Design library referenced, all you have to do is run the [scaffold](https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/?tabs=dotnet-core-cli) command to generate the model with all customizations applied. For example:

> dotnet ef dbcontext scaffold "data source=localhost;initial catalog=Northwind;persist security info=True;Integrated Security=SSPI;TrustServerCertificate=True;" Microsoft.EntityFrameworkCore.SqlServer -o Models -c NorthwindEntities -f  --co
ntext-dir Context

**Comment by jdanielpa** [comment]
I am getting closer.  I was able to install the extension and bring up the UI. When I Generate Rules, I get:

Error writing rule to file NextGenPlasticsEntities-rules.json  Could not load file or assembly System.ComponentModel.Annotations v4.2.0.0 or one of its components.  The system cannot find the file specified.  

It did create the rules.json file in the target project but it only contains:

{
   "Name": "NextGenPlasticsEntities",
   "PreserveCasingUsingRegex": false,
   "IncludeUnknownSchemas": false,
   "SplitEntityTypeConfigurations": false,
   "Schemas": [
      ""
   ]
}

**Comment by R4ND3LL** [comment]
Thanks for trying.  Looks like you should have better luck with the CLI tool for now.  I'll look into the extension issue.

**Comment by jdanielpa** [comment]
I am getting a strange error when trying to install the CLI tool as well:

>dotnet tool install --global EntityFrameworkRuler
C:\Users\####\AppData\Local\Temp\f9d9ce52-e56b-4d81-b250-fee1e28899a0\restore.csproj : error NU1301: Unable to load
the service index for source https://pkgs.dev.azure.com/JJVProjectLifeCycle/_packaging/jjvmetrologylifecycle/nuget/v3/i
ndex.json.
The tool package could not be restored.
Tool 'entityframeworkruler' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool


Any ideas on why I see this?
Thanks again for all the help.

**Comment by R4ND3LL** [comment]
Is this in a _Developer Powershell_ window within VS?  I just tested again locally and it worked fine.

You can try tacking on the version arg to see if that helps:
> dotnet tool install --global EntityFrameworkRuler --version 1.0.28

**Comment by jdanielpa** [comment]
That did it - I had to specify the version.  I now have a rules.json file.  I have a couple more questions (sorry for so many :( ):  

- I can bring up the DB Context Rule Editor now and I can see all of my tables with the exception of one.  The one that is missing uses table splitting in the edmx.  Is that going to be a problem or **is table splitting supported**?

When I try the scaffold command in PowerShell I get an error.  Here is the command I am running:
- > Scaffold-DbContext 'Data Source=localhost;Initial Catalog=NextGenPlastics' Microsoft.EntityFrameworkCore.SqlServer

Here is the error it gives:
Scaffold-DbContext : The term 'Scaffold-DbContext' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At line:1 char:1
+ Scaffold-DbContext 'Data Source=localhost;Initial Catalog=NextGenPlas ...
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Scaffold-DbContext:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


I assume I am not using the scaffolding command in PowerShell properly?  

Thanks again!

**Comment by R4ND3LL** [comment]
The bigger question is, is table splitting supported by the Reverse Engineer?  From Microsoft, the answer is no: 
[scaffolding limitations](https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/?tabs=dotnet-core-cli#limitations)

Perhaps it is possible to apply table splitting using rules.json but that's not planned right now.  At minimum, I'd need to see an example of what that looks like in the code-first approach and see if it can be forced during the DB-first approach.  Would need some R&D.  

As for the scaffold command, from the Developer Powershell use the format:
>dotnet ef dbcontext scaffold "data source=localhost;initial catalog=NextGenPlastics;persist security info=True;Integrated Security=SSPI;TrustServerCertificate=True;" Microsoft.EntityFrameworkCore.SqlServer -o Models -c NextGenPlasticsEntities -f --context-dir Context

**Comment by jdanielpa** [comment]
I might have more than one problem based on the scaffolding limitations.  Looking at the link you sent not only is table splitting not supported but also inheritance hierarchies.  This is another thing I do heavily.  Here is a screenshot of just a portion of the full edmx I am working towards replacing.  You will see RecipeZone is the SQL table.  There are close to 100 inheritance classes in the code using RecipeZone.  They map to RecipeZone thru the RecipeName field using table mappings.  Is this also something that cannot be done?  I need to determine if I am stuck in .netframework 4.8 which would be crazy or is there another solution?

Thank you for the help and info.  

![image](https://user-images.githubusercontent.com/119625172/205740816-5e08e1ca-ab8f-40a5-854f-a38a6f1564e9.png)

**Comment by jdanielpa** [comment]
I am still having troubles with scaffolding:

> dotnet ef dbcontext scaffold "data source=localhost;initial catalog=NextGenPlastics;persist security info=True;Integrated Security=SSPI;TrustServerCertificate=True;" Microsoft.EntityFrameworkCore.SqlServer -o Models -c NextGenPlasticsEntities -f --context-dir Context
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-ef does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

**Comment by R4ND3LL** [comment]
It sounds to me like your dotnet ef tools are outdated.   try the following:
> dotnet tool install --global dotnet-ef
> dotnet tool update --global dotnet-ef
> dotnet tool restore

Go [here](https://learn.microsoft.com/en-us/ef/core/cli/dotnet) for details.

after that, run "dotnet ef".  It should indicate 7.0.0 is installed.

Regards to your inheritance dilemma, Reverse Engineer is generally just not an option for you.  Unless I figure out a way to make this available via EF Ruler, which won't be very soon.   

The beauty of the Reverse Engineer, however, is that it produces a model that is basically ready to use as Code-First.  So the best option for you right now is to use EF Ruler and Reverse Engineer to get as close as possible to what you need, just as a starting point.   Then adjust the entity configurations to apply the appropriate inheritance ([as described here](https://learn.microsoft.com/en-us/ef/core/modeling/inheritance)).

Going forward, you will then be doing Code-First (like probably 90% of the people that use EFCore).  This is a big shift in workflow because it means you apply DB changes via code and then run "dotnet ef database update".  It's a good process if your project can support it.

**Comment by jdanielpa** [comment]
You were right - the tools were out of date.  When I run your command I get an error stating:

Unrecognized option '--context-dir'

If I remove that flag --context-dir Context then I get the following:

>dotnet ef dbcontext scaffold "data source=localhost;initial catalog=NextGenPlastics;persist security info=True;Integrated Security=SSPI;TrustServerCertificate=True;" Microsoft.EntityFrameworkCore.SqlServer -o Models -c NextGenPlasticsEntities -f
EF Ruler detected Entity Framework v7.0.0.0
Rule loader resolved target assembly: JJV.NGP.Data
**Unable to open NextGenPlasticsEntities-rules.json**
EF Ruler loaded 0 rule file(s).
To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
The column 'dbo.Lot.Active' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details.
The column 'dbo.MeasuredPlastic.Active' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details.
The column 'dbo.PlasticType.Active' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details.
The column 'dbo.Sample.Active' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details.
The column 'dbo.TargetLens.Active' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details.
The column 'dbo.TargetPlastic.Active' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details.
The column 'dbo.Users.Active' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details.
The column 'dbo.VirtualLens.Active' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details.


The classes generate but seem to ignore the .json file.  I have PowerShell in the root folder of the Data project which is the same location as the 'NextGenPlasticsEntities-rules.json' file.

Any idea on why it would say Unable to open NextGenPlasticsEntities-rules.json ?

**Comment by R4ND3LL** [comment]
Did you edit the Rule file using the UI Editor (and saved changes)?  If so, your json model is probably different than what the Design library is expecting.  I made a change in the VS Extension version, but you are using v1.0.28 of Design, which is prior to that change.   Long story short, I need to push updated NuGet packages to sync up with the VSIX.  I'll do that shortly.

To get up and running immediately, you can run "efruler -g..." again to regenerate the json, don't make edits with the UI Editor, and then run the scaffold.  It should work fine.

>  I need to determine if I am stuck in .netframework 4.8 which would be crazy or ..

BTW, you are not stuck on 4.8 either way.   Old Entity Framework 6.4 works perfectly fine with .net core projects.  I'm in that situation now with some large projects and am using EF Ruler as a means to migrate to EF Core 7.

**Comment by jdanielpa** [comment]
Good point - I guess I could keep a 4.8 version of the data model with the edmx around while we workout the issues with EF Core. 

Can you let me know when you update the nuget package so I can edit with the UI Editor?  Thanks for all the help today - I really appreciate it.  I am more than happy to help flush out issues with table splitting and inheritance in the future if ever needed.

**Comment by R4ND3LL** [comment]
NuGet packages updated v1.1.0..   should be 100% compatible with your VSIX version now

**Comment by jdanielpa** [comment]
Thanks!  I just tried it and I think I am still doing something wrong.

First I updated the nuget package.
Then I ran the Generate DB Conext Rules from EDMX and even though my project references System.ComponentModel.Annotations, it throws this error:

![image](https://user-images.githubusercontent.com/119625172/206029292-517f59a4-7a9d-4d6a-96b6-66d0ccecda36.png)


It creates the -rules.json file but the file looks like this:

{
   "Name": "NextGenPlasticsEntities",
   "PreserveCasingUsingRegex": false,
   "IncludeUnknownSchemas": false,
   "SplitEntityTypeConfigurations": false,
   "Schemas": [
      ""
   ]
}

**Comment by R4ND3LL** [comment]
While I can't reproduce this error, I published another version of the [extension](https://marketplace.visualstudio.com/items?itemName=Randell.EF-Ruler) with some changes that may help.   Let me know if it works better.

Remember that the [command line tool](https://www.nuget.org/packages/EntityFrameworkRuler/) can also be used as backup if generation fails using the extension.

**Comment by jdanielpa** [comment]
I really appreciate all the help you are giving me and I think I am close but I am still having problems.

So maybe I am not understanding what to do.  Let me start from the beginning and maybe you can tell me where I am going wrong:
1. With no rules.json file, using the CLI I run: >efruler -g "D:\JJV\Development\Workspaces\ProjectLifeCycle\NGPMetrology\Main\JJV.NGP.EDMX\NGPContext.edmx" "D:\JJV\Development\Workspaces\ProjectLifeCycle\NGPMetrology\Main\JJV.NGP.Data"
This generates a rules.json file in the Data project.

2. From the CLI I run: >dotnet ef dbcontext scaffold "data source=localhost;initial catalog=NextGenPlastics;persist security info=True;Integrated Security=SSPI;TrustServerCertificate=True;" Microsoft.EntityFrameworkCore.SqlServer -o Models -c NextGenPlasticsEntities -f
This creates all the classes in Data project.  So far, so good.

2. I modify the rules.json (using the DB Context Rule Editor) file to update any Table and/or Column names that are not correct
3. From the CLI I run:>efruler -a "D:\JJV\Development\Workspaces\ProjectLifeCycle\NGPMetrology\Main\JJV.NGP.Data"
I get "Error: Unable to open NextGenPlasticsEntities-rules.json"

What am I doing wrong?

Thanks again!

**Comment by R4ND3LL** [comment]
Before step 2, you should ensure that you have referenced the [EntityFrameworkRuler.Design](https://www.nuget.org/packages/EntityFrameworkRuler.Design/) library (from the Data project).  

This library serves 1 purpose: it automatically interacts with the EF Core scaffolding process to apply all the rules in the local folder.

So after modifying the json file using the editor, simply rerun the scaffold command (step 2) as if you made a DB change.  the generated entities will reflect your customizations automatically.   

Forget about the "efruler -a" command.

**Comment by jdanielpa** [comment]
I already have the [EntityFrameworkRuler.Design](https://www.nuget.org/packages/EntityFrameworkRuler.Design/) referenced.

When I rerun step 2 - It overwrites my rules.json file and creates the classes with the old names.  I lose the changes I made.

Side note:  After the rerun of step 2 if I try to update the rules file again and run the step 2 command again I get "Build failed.".  I have to remove all the classes that were created before I can run the step 2 command again.  Regardless, it just overwrites the rules.json file

**Comment by jdanielpa** [comment]
Maybe I am not using the Editor properly.  Here is what I see when I load the editor:
![image](https://user-images.githubusercontent.com/119625172/206326590-dc311e7f-a708-4aa3-b316-d1064bd27f37.png)
Notice TargetLen and VirtualLen tables.

If I want the table to be TargetLens, do I edit the Expected Entity Name, New Name or both?

**Comment by R4ND3LL** [comment]
Only set New Name to TargetLens.    
It is normal to see your changes to Expected Entity Name to be overwritten (corrected), but New Name should NOT be overwritten when you run the scaffold.   is that happening?

**Comment by jdanielpa** [comment]
Yes.  I set New Name to TargetLens, rerun scaffolding and the result class is TargetLen.  If I open the Rule Editor, New Name is set back to TargetLen

**Comment by R4ND3LL** [comment]
It sounds like the json file can't be opened during the scaffolding either, so at the end a new file is being initialized (overwriting your changes).   

When you run the scaffold command, you should see confirmation that the file is loaded such as:
>Build started...
Build succeeded.
EF Ruler detected Entity Framework v7.0.0.0
Rule loader resolved target assembly: JJV.NGP.Data
EF Ruler **loaded 1 rule file(s).**

Can you tell me what it says when you run it?  But first, double-check that you have updated your [EntityFrameworkRuler.Design](https://www.nuget.org/packages/EntityFrameworkRuler.Design/) reference to the latest in the JJV.NGP.Data project.  Currently v1.1.1

**Comment by jdanielpa** [comment]
I am on the latest EFRuler.Design.  Here is everything I get:

>dotnet ef dbcontext scaffold "data source=localhost;initial catalog=NextGenPlastics;persist security info=True;Integrated Security=SSPI;TrustServerCertificate=True;" Microsoft.EntityFrameworkCore.SqlServer -o Models -c NextGenPlasticsEntities -f
EF Ruler detected Entity Framework v7.0.0.0
Rule loader resolved target assembly: JJV.NGP.Data
EF Ruler loaded 1 rule file(s).
To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
The column 'dbo.Lot.Active' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details.
The column 'dbo.MeasuredPlastic.Active' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details.
The column 'dbo.PlasticType.Active' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details.
The column 'dbo.Sample.Active' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details.
The column 'dbo.TargetLens.Active' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details.
The column 'dbo.TargetPlastic.Active' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details.
The column 'dbo.Users.Active' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details.
The column 'dbo.VirtualLens.Active' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details.
Info: DbContext rule file written to NextGenPlasticsEntities-rules.json
Updated NextGenPlasticsEntities-rules.json in 62ms

**Comment by jdanielpa** [comment]
The other thing I notice is after I run the command, I cannot run it again until I delete every class it created and undo modifications to any classes it updated.  If I don't do this then the command just returns Build failed.

**Comment by R4ND3LL** [comment]
That's helpful, but we could use more info.   Update **Design** ref to 1.1.3 (just published) then add -v to the scaffold command for verbose logging.  Let's see what that says

**Comment by jdanielpa** [comment]
Here you go...
[scaffoldResults.txt](https://github.com/R4ND3LL/EntityFrameworkRuler/files/10189534/scaffoldResults.txt)

**Comment by jdanielpa** [comment]
I made a mistake! - It is **not** overwriting the rules.json file when it runs.  It is just creating the classes for the tables with the old names.  I was seeing the old info in the rules file because I have to undo all changes after I run the scaffolding command if I want to run it again.  So at this point the issue is even though I set TagetLen to TargetLens, it still creates a class called TargetLen. 

Sorry for the incorrect info :(

**Comment by R4ND3LL** [comment]
I do see an issue, I believe related to the table inheritance.  I'm investigating. However, it would be most efficient if I could test using your project.  Could you send me a copy of the EDMX and  DB creation script (zipped up)?  With those 2 pieces, I can test it all, and possibly also investigate whether it's possible to reverse engineer entities with inheritance properly.

If you want, the zip can be pw protected and you can pass the pw to me via [one time secret](https://onetimesecret.com/)

The other thing is I was expecting to see some log messages there that were not.  Suggests that the Design reference was not >= 1.1.3

**Comment by jdanielpa** [comment]
Here you go.  I also included a few other files: 

1. EFCore folder (Data Porject) has the t4 templates I am using to add in namespaces as well as decorate the properties with INotifyPropertyChanged interface.  I created these files when I was trying to use EF Core Power Tools last week.  Your tool seems to be picking them up as well :)
2. PartialClasses folder (Data Project).  This contains other properties that are either not stored in the database or are created from deserializing a field from the database. 


Thanks for all your time and effort!

**Comment by R4ND3LL** [comment]
Got it thanks. You can remove the attachment now if you want to remove from public eye

**Comment by R4ND3LL** [comment]
This issue is resolved.  Extension and nuget packages updated to v1.1.5.

Tested with your EDMX and DB and it works well.

Note, the compile error youre getting after scaffolding is because you are scaffolding into a project with existing code files.  the scaffold process does not clear out entity files before writing to the model folder.  when doing renaming of tables, you will likely end up with an old file with the old name that existed before, and EF will write a new file with the new name.  You have to reconcile this yourself.

**Comment by jdanielpa** [comment]
What I have discovered is I have to delete the partial classes as well as my engine class.  Then I can run the scaffolding tool without error.  Then I add the deleted files back in.  Seems a bit strange I have to do this but it works!  If I don't delete them, the scaffolding throws errors on these classes saying it cant find properties.  The properties it can't find are properties the scaffolding command will build :)

Last questions.. for now :)  Can you point me to an example of how to do table splitting and inheritance using Code First?  No problem if you don't have anything off the top of your head.

Thank you so much for all the help on this problem and for the quick response.

**Comment by R4ND3LL** [comment]
You can add "--no-build” to the scaffold command and it will skip the build and use the last built assembly instead — may be good for your case if you are running into compile issues sometimes.


The inheritance link: https://learn.microsoft.com/en-us/ef/core/modeling/inheritance


Can you explain briefly what kind of inheritance you have setup in that EDMX?  I didn’t see it during my high-level review. I may take a look later to see if it can be reverse-engineered.

**Comment by jdanielpa** [comment]
I will test the --no build option.  Thanks

I did not include the inheritance in the EDMX I sent you - I didn't want to try and tackle too many things at one time.  If you look at this EDMX screenshot, you will see what I am currently doing with EDMX:

![image](https://user-images.githubusercontent.com/119625172/206761293-b061e15c-d499-48dd-a626-c8e866145fca.png)

You will see the table RecipeZone (Recipe in SQL) is the base type for many other entities.  There are no tables for the inheriting entities in SQL - only the RecipeZone table.  Using table mappings, the entities map to there type based on a field stored in RecipeZone called "RecipeClassName".  For example, the image shows the table mapping for RecipeZoneOffset to RecipeZone.

The reason for doing this is because regardless of the recipe we are using, it is always a RecipeZone.  RecipeZone is related to other tables with 1 to many relationships.  All recipes have 0 to n records in the other tables.

Make sense?  If not, I could probably build another EDMX with this demonstrated.

Also, can you tell me where do to go to rate your tool?
Thanks

**Comment by jdanielpa** [comment]
This I believe describes what I am doing:

Table per Hierarchy (TPH): Enable polymorphism by denormalizing the SQL schema, and utilize a type discriminator column that holds type information.

**Comment by R4ND3LL** [comment]
> Also, can you tell me where do to go to rate your tool? Thanks

You can hit the Star button here on Github.  Other than that, you can add a review on the VS Extension at this link: 
[https://marketplace.visualstudio.com/items?itemName=Randell.EF-Ruler&ssr=false#review-details](https://marketplace.visualstudio.com/items?itemName=Randell.EF-Ruler&ssr=false#review-details)

Much appreciated!

Note, I also recently setup Github Sponsorship (Sponsor button).  I will never request sponsorship from anybody, but people may consider it as a means to show appreciation or prioritize requests.  

In the meantime, I created another ticket on the TPH topic and will post updates on it there as I find out more.

**Comment by jdanielpa** [comment]
The Sponsorship link is not working.  It goes to PayPal but says:
Sorry.
It looks like nothing was found at this location. Maybe try one of the links below or a search?

**Comment by R4ND3LL** [comment]
Whoa, that's not good.  These are 2 options for sponsorship; thru GitHub and PayPal:
- https://github.com/sponsors/R4ND3LL
- https://paypal.me/R4ND3LL?country.x=CA&locale.x=en_US

Sorry, I verified with a proxy that the PayPal option does not yet work outside of Canada.  Maybe a delay with PayPal, I'm not sure.. but the first link does work.

**Comment by R4ND3LL** [comment]
Many thanks, @jdanielpa!   Very much appreciated.

**Comment by jdanielpa** [comment]
You are welcome!
