### ISSUE TITLE
TPH does not use the New Name property

### ISSUE THREAD

**Issue by jdanielpa** [R4ND3LL/EdmxRuler#15]
BaseEntryExit is TPH and the fields have New Name set to Booleans and Doubles.

![image](https://user-images.githubusercontent.com/119625172/214573262-4d84d681-ffb6-49ba-aca1-1aece3e38940.png)

ArcAutoRadius Base Type is BaseEntryExit.  Resulting code for ArcAutoRadius show Expected Name instead of New Name

>     public virtual ICollection<EntryExitBoolean> EntryExitBooleans { get; set; } = new List<EntryExitBoolean>();
> 
> 
>     public virtual ICollection<EntryExitDouble> EntryExitDoubles { get; set; } = new List<EntryExitDouble>();

Also, using the EDMX the Booleans and Doubles properties would reside in the BaseEntryExit.  With EF Core it resides in ArcAutoRadius.  Is there a reason the properties can no longer be in BaseEntryExit?

**Comment by R4ND3LL** [comment]
Another issue with default EF Core mapping.  Fixed in v1.2.8 (which is building now)

**Comment by jdanielpa** [comment]
I just tries 1.2.9 but still see this issue.  Thoughts?
This might be on my side.  Standby...
Nope.  Just confirmed it is not working.

Also, is there a way to get the properties on the base class to reside at the base class instead of being copied to every class with inheritance?  With the EDMX, Booleans and Doubles were only in BaseEntryExit, not all the inheriting classes.

**Comment by R4ND3LL** [comment]
Most of the methods like GetProperties() are recursive, meaning they include the props of base type entities automatically. You need to adjust your T4 to filter out the props to only that of the declaring type such as:

```csharp
EntityType.GetProperties().Where(o => o.DeclaringEntityType == EntityType)
```
Same for indexes, foreign keys, etc in the configuration:
[EntityTypeConfiguration.t4](https://github.com/R4ND3LL/EntityFrameworkRuler/blob/main/src/Tests/NorthwindTestDesign/CodeTemplates/EFCore/EntityTypeConfiguration.t4)

Same for [EntityType.t4](https://github.com/R4ND3LL/EntityFrameworkRuler/blob/main/src/Tests/NorthwindTestDesign/CodeTemplates/EFCore/EntityType.t4)
